REM ECHO Checking the log file for errors...
REM FINDSTR /C:"RC (return code) = 0" %workDir%\%filenm%_Log.txt && (ECHO Deployment was successful. 
REM ECHO Email is sent out...
REM cscript //nologo success_mail_DEV.vbs %workDir%  'passing the directory param. here.
REM ECHO Press ENTER to exit...
REM GOTO offshore) || (ECHO Deployment was not successful. Errors were found!
REM ECHO Email is sent out...
REM ECHO Press ENTER to exit...
REM cscript //nologo fail_mail_DEV.vbs %workDir%  'and here
REM GOTO offshore)
cscript SendEmail.vbs  arg_1  arg_2  "Hello World"